# Mathematical Foundation for AI and Machine Learning
# Practice Lab

In [6]:
import sys
import numpy as np
import pandas as pd
print("Numpy: {}".format(np.__version__))
print("Pandas: {}".format(pd.__version__))

Numpy: 2.0.1
Pandas: 2.2.2


In [ ]:
# Defining a scalar
x = 7

In [7]:
# defining a vector
x = np.array((1,2,3))
x

array([1, 2, 3])

In [10]:
print(f' dimension of vector {x.shape}')
print(f' size of vector {x.size}')

 dimension of vector (3,)
 size of vector 3


In [11]:
x= np.matrix([[1,2,3],[4,5,6],[7,8,9]])
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [12]:
print(f' dimension of vector {x.shape}')
print(f' size of vector {x.size}')

 dimension of vector (3, 3)
 size of vector 9


In [13]:
x = np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
x = np.ones((3,3,3))
x

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [15]:
print(f' dimension of vector {x.shape}')
print(f' size of vector {x.size}')

 dimension of vector (3, 3, 3)
 size of vector 27


In [17]:
# indexing
A = np.ones((5,5), dtype = int)
A

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
# Indexing starts at 0
A[0,1] = 2
A

array([[1, 2, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [25]:
A[1,4] = 5
A

array([[4, 2, 1, 1, 1],
       [5, 1, 1, 1, 5],
       [4, 1, 1, 1, 1],
       [4, 1, 1, 1, 1],
       [4, 1, 1, 1, 1]])

In [30]:
# Matrix Operations
A = np.matrix([[1,2],[3,4]])
B = np.ones([2,2], dtype = int)

In [31]:
A

matrix([[1, 2],
        [3, 4]])

In [32]:
B

array([[1, 1],
       [1, 1]])

In [33]:
# Addition or Sum
C = A + B
C

matrix([[2, 3],
        [4, 5]])

In [34]:
# Subtraction
C = A - B
C

matrix([[0, 1],
        [2, 3]])

In [36]:
# Multiplication
C = A*B
C

matrix([[3, 3],
        [7, 7]])

In [37]:
# Dot Product same as Multiplication
D  = A.dot(B)
D

matrix([[3, 3],
        [7, 7]])

In [39]:
# Matrix transpose
A = np.array(range(9))
A = A.reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
B = A.T
B

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [48]:
# Tensors
A  = np.ones([3 for x in range(10)])
print(f' dimension of vector {A.shape}')
print(f' size of vector {A.size}')

 dimension of vector (3, 3, 3, 3, 3, 3, 3, 3, 3, 3)
 size of vector 59049
